name: mygym
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.13.0=py37h06a4308_0
  - aiohttp=3.7.4=py37h27cfd23_1
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - astor=0.8.1=py37h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py37h06a4308_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blinker=1.4=py37h06a4308_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - chardet=3.0.4=py37h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - coverage=5.5=py37h27cfd23_2
  - cryptography=3.4.7=py37hd23ed53_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - curl=7.78.0=h1ccaba5_0
  - cycler=0.10.0=py37_0
  - cython=0.29.24=py37h295c915_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py37h295c915_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.2.2=h20bf706_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - gettext=0.21.0=hf68c758_0
  - git=2.32.0=pl5262hc120c5b_1
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.36.1=py37h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.2=pyhd3eb1b0_0
  - imageio=2.8.0=py_0
  - importlib-metadata=4.6.4=py37h06a4308_0
  - importlib_metadata=4.6.4=hd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.2.0=py37h06a4308_1
  - ipython=7.26.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py37h06a4308_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - jupyter_kernel_gateway=2.5.0=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py37h2531618_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py37h06a4308_0
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py37hf046da1_1
  - mpich=3.3.2=hc856adb_0
  - multidict=5.1.0=py37h27cfd23_2
  - munkres=1.1.4=py_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.4.3=py37h06a4308_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pcre2=10.35=h14c3975_1
  - perl=5.26.2=h14c3975_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=6.2.1=py37h34e0f95_0
  - pip=21.2.2=py37h06a4308_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyhca03da5_0
  - protobuf=3.17.2=py37h295c915_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py37h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - pytorch=1.8.1=py3.7_cuda10.1_cudnn7.6.3_0
  - pyzmq=22.2.1=py37h295c915_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.1=py37h292c36d_2
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - termcolor=1.1.0=py37h06a4308_1
  - terminado=0.9.4=py37h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.9.1=py37_cu101
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.62.1=pyhd3eb1b0_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py37h27cfd23_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - alabaster==0.7.12
    - atari-py==0.2.9
    - babel==2.9.1
    - bbox==0.9.2
    - cloudpickle==1.3.0
    - commentjson==0.9.0
    - configargparse==1.5.2
    - configargparser==0.0.2
    - cvae==0.0.3
    - docutils==0.17.1
    - flatbuffers==2.0
    - future==0.18.2
    - gast==0.2.2
    - gym==0.17.0
    - imagesize==1.2.0
    - joblib==1.0.1
    - jsonmerge==1.8.0
    - keras==2.7.0rc2
    - keras-applications==1.0.8
    - lark-parser==0.7.8
    - libclang==12.0.0
    - matplotlib==3.1.3
    - numpy==1.18.5
    - opencv-python==4.2.0.34
    - pandas==1.0.1
    - pillow-simd==7.0.0.post3
    - psutil==5.8.0
    - pyaml==21.8.3
    - pybullet==2.6.6
    - pyglet==1.5.0
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyquaternion==0.9.9
    - pytz==2021.1
    - pyyaml==5.4.1
    - qibullet==1.4.0
    - scikit-learn==0.24.2
    - sklearn==0.0
    - snowballstemmer==2.1.0
    - sphinx==4.2.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stable-baselines==2.10.2
    - stable-baselines3==1.2.0
    - tensorboard==1.15.0
    - tensorflow==1.15.5
    - tensorflow-estimator==1.15.1
    - tensorflow-io-gcs-filesystem==0.21.0
    - threadpoolctl==2.2.0
    - wheel==0.37.0
prefix: /home/michal/anaconda3/envs/mygym
