name: mygym
channels:
  - defaults
  - pytorch
dependencies:
  - matplotlib
  - cudatoolkit==10.1.243
  - pytorch::torchvision
  - pytorch::pytorch
  - numpy
  - matplotlib-base
  - pip
  - python=3.7
  - pillow==6.2.1
  - openssl
  - cython
  - git
  - dill
  - flake8
  - imageio=2.8
  - tensorflow>=1.15.0
  - tensorflow-gpu>=1.15.0
  - tqdm
  - imageio
  - notebook
  - jupyter_kernel_gateway
  - mpi4py==3.0.3
  - pip:
    - matplotlib==3.1.3
    - pandas==1.0.1
    - future
    - gym==0.17.0
    - opencv-python==4.2.0.34
    - pybullet==2.6.6
    - qibullet==1.4.0
    - cvae
    - scipy
    - 'git+https://github.com/nightrome/cocostuffapi.git#subdirectory=PythonAPI'
    - pillow-SIMD
    - PyQt5
    - commentjson #for generate_dataset
    - bbox
    - pyrr #dope
    - pyyaml #dope
    - jsonmerge
    - open3d-python
    - dill
    - stable-baselines3[extra]
    - configargparse
    - stable-baselines
    - sklearn
prefix: /home/megi/miniconda3/envs/mygym

