name: mygym_clean
channels:
  - pytorch
  - defaults
dependencies:
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py37h2531618_0
  - mpi=1.0=mpich
  - ninja=1.10.2=hff7bd54_1
  - pip=21.2.2=py37h06a4308_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.11=h12debd9_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - pip:
    - atari-py==0.2.9
    - babel==2.9.1
    - bbox==0.9.2
    - colorama==0.4.5
    - cloudpickle==1.3.0
    - commentjson==0.9.0
    - configargparse==1.5.2
    - configargparser==0.0.2
    - Cython==0.29.24
    - dill==0.3.4
    - docutils==0.17.1
    - flatbuffers==2.0
    - future==0.18.2
    - gast==0.2.2
    - getkey==0.6.5
    - gym==0.17.0
    - imageio==2.21.1
    - imagesize==1.2.0
    - joblib==1.0.1
    - keras==2.7.0rc2
    - keras-applications==1.0.8
    - lark-parser==0.7.8
    - libclang==12.0.0
    - matplotlib==3.1.3
    - mpi4py==3.1.4
    - numpy==1.18.5
    - opencv-python==4.2.0.34
    - packaging==21.0
    - pandas==1.0.1
    - Pillow==9.2.0
    - protobuf==3.19.0
    - psutil==5.8.0
    - pyaml==21.8.3
    - pybullet==2.6.6
    - pyglet==1.5.0
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyquaternion==0.9.9
    - pytz==2021.1
    - pyyaml==5.4.1
    - qibullet==1.4.0
    - setuptools==52.0.0
    - scikit-learn==1.0.2
    - scipy==1.7.1
    - sklearn==0.0
    - snowballstemmer==2.1.0
    - stable-baselines==2.10.2
    - stable-baselines3==1.2.0
    - tensorboard==1.15.0
    - tensorflow==1.15.5
    - tensorflow-estimator==1.15.1
    - tensorflow-io-gcs-filesystem==0.21.0
    - torch==1.8.1
    - torchvision==0.9.1
    - tqdm==4.62.1
    - typing_extensions==3.10.0.0
    - wheel==0.37.0
prefix: /home/michal/anaconda3/envs/mygym 
