[project]
name = "myGym"
version = "3.10.0"
description = "myGym"
authors = [
    {name = "Incognite group CIIRC CVUT", email = "michal.vavrecka@cvut.cz"},
    {name = "Incognite group CIIRC CVUT"},
]
dependencies = [
    "cloudpickle>=3.0.0",
    "ffmpeg>=1.4",
    "ipykernel>=6.29.2",
    "ipython>=8.22.1",
    "numpy>=1.26.4",
    "scipy>=1.12.0",
    "pandas>=2.2.0",
    "pyaml>=23.12.0",
    "pyyaml>=6.0.1",
    "scikit-image>=0.22.0",
    "scikit-learn>=1.4.1.post1",
    "trimesh>=4.1.4",
    "opencv-python==4.9.0.80",
    "pybullet==3.2.6",
    "open3d==0.18.0",
    "stable-baselines3==2.4.0",
    "tensorboard>=2.18.0",
    "torch=2.5.1",
    "torchvision>=0.17.1",
    "torchaudio>=2.2.1",
    "matplotlib>=3.8.3",
    "pyquaternion>=0.9.9",
    "commentjson>=0.9.0",
    "gymnasium>=1.0.0",
    "protobuf<4,>3",
    "stable-baselines3>=2.4.0",
    "shimmy==0.2.1",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "MIT License\n\nCopyright (c) 2024 CIIRC, CTU in Prague\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n\n"}
maintainers = [
    {email = "michal.vavrecka@cvut.cz"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
]

[project.urls]
Homepage = "https://mygym.readthedocs.io"
Downloads = "https://github.com/incognite-lab/myGym/tree/develop"
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pdm]
distribution = true
